"""Generate the README's tool list from capabilities/*/*.json, so it can never go stale.

    python scripts/gen_tools_table.py            # rewrite the block in README.md
    python scripts/gen_tools_table.py --check    # CI: exit 1 if README.md is out of date
"""
import argparse
import ast
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

START = "<!-- TOOLS:START"
END = "<!-- TOOLS:END -->"


def default_off(toolswitch: Path) -> frozenset[str]:
    """The DEFAULT_OFF ids from toolswitch.py, read without importing it (one source of truth for the server
    and the README). Missing file: nothing is off."""
    if not toolswitch.exists():
        return frozenset()
    for node in ast.walk(ast.parse(toolswitch.read_text(encoding="utf-8"))):
        if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "DEFAULT_OFF" for t in node.targets):
            value = node.value.args[0] if isinstance(node.value, ast.Call) else node.value
            return frozenset(ast.literal_eval(value))
    raise SystemExit(f"{toolswitch} has no DEFAULT_OFF")


def load(cap_dir: Path, exclude: set[str]) -> dict[str, list[dict]]:
    by_cat = defaultdict(list)
    for f in sorted(cap_dir.glob("*/*.json")):
        m = json.loads(f.read_text(encoding="utf-8"))
        if m["category"] in exclude or m["id"] in exclude:
            continue
        by_cat[m["category"]].append(m)
    return dict(sorted(by_cat.items()))


def cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def render(by_cat: dict[str, list[dict]], off: frozenset[str] = frozenset()) -> str:
    total = sum(len(v) for v in by_cat.values())
    out = [f"{START} (generated by scripts/gen_tools_table.py; do not edit by hand) -->",
           f"**{total} tools** in {len(by_cat)} groups. `write` tools change something; 🔒 = off until you enable it "
           "(see [Security](#security)).", ""]
    for cat, caps in by_cat.items():
        out += [f"<details><summary><b>{cat}</b> ({len(caps)})</summary>", "",
                "| Tool | What it does | Risk | Needs |", "|---|---|---|---|"]
        for m in sorted(caps, key=lambda m: m["id"]):
            needs = ", ".join(m.get("requires", [])) or "nothing"
            risk = m.get("risk", "") + (" 🔒" if m["id"] in off else "")
            out.append(f"| `{m['id']}` | {cell(m.get('description', ''))} | {risk} | {cell(needs)} |")
        out += ["", "</details>", ""]
    out.append(END)
    return "\n".join(out)


def splice(readme: str, block: str) -> str:
    i, j = readme.find(START), readme.find(END)
    if i < 0 or j < i:
        raise SystemExit(f"README is missing the {START} ... {END} markers")
    return readme[:i] + block + readme[j + len(END):]


COUNT = re.compile(r"<!--count:(total|ready|off|needs)-->.*?<!--/count-->")


def counts(by_cat: dict[str, list[dict]], off: frozenset[str] = frozenset()) -> dict[str, int]:
    """Three groups that never overlap: off (default-off), ready (on, needs nothing), needs (on, needs a backend)."""
    caps = [m for v in by_cat.values() for m in v]
    n_off = sum(1 for m in caps if m["id"] in off)
    ready = sum(1 for m in caps if m["id"] not in off and not m.get("requires"))
    return {"total": len(caps), "ready": ready, "off": n_off, "needs": len(caps) - ready - n_off}


def fill_counts(text: str, n: dict[str, int]) -> str:
    """Replace every <!--count:KIND-->…<!--/count--> in prose, so no number in the README is typed by hand."""
    return COUNT.sub(lambda m: f"<!--count:{m.group(1)}-->{n[m.group(1)]}<!--/count-->", text)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--capabilities", type=Path, default=Path("capabilities"))
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--toolswitch", type=Path, default=Path("toolswitch.py"), help="where DEFAULT_OFF lives")
    p.add_argument("--exclude", default="", help="comma-separated categories or tool ids to leave out")
    p.add_argument("--check", action="store_true", help="exit 1 if the README is stale")
    a = p.parse_args(argv)
    exclude = {c for c in a.exclude.split(",") if c}
    old = a.readme.read_text(encoding="utf-8")
    by_cat = load(a.capabilities, exclude)
    off = default_off(a.toolswitch)
    new = fill_counts(splice(old, render(by_cat, off)), counts(by_cat, off))
    if a.check:
        if new != old:
            print("README tool list is stale: run python scripts/gen_tools_table.py", file=sys.stderr)
            return 1
        return 0
    a.readme.write_text(new, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
