"""Generate the README's install section: one-click buttons, one-line commands and per-client configs.

Every link and snippet is built from one package name, so a rename is a single re-run:
    python scripts/gen_install.py --package my-server
    python scripts/gen_install.py --package my-server --check   # CI: exit 1 if README.md is stale
"""
import argparse
import base64
import json
import sys
from pathlib import Path
from urllib.parse import quote, urlencode

START = "<!-- INSTALL:START"
END = "<!-- INSTALL:END -->"


def compact(obj) -> str:
    return json.dumps(obj, separators=(",", ":"))


def links(pkg: str) -> dict[str, str]:
    stdio = {"command": "uvx", "args": [pkg]}
    cursor_cfg = base64.b64encode(compact(stdio).encode()).decode()
    vscode_cfg = compact({"type": "stdio", **stdio})
    vscode = "https://insiders.vscode.dev/redirect/mcp/install?" + urlencode({"name": pkg, "config": vscode_cfg}, quote_via=quote)
    return {
        "cursor": "https://cursor.com/en/install-mcp?" + urlencode({"name": pkg, "config": cursor_cfg}, quote_via=quote),
        "vscode": vscode,
        "vscode_insiders": vscode + "&quality=insiders",
    }


def block(pkg: str, fence: str = "```") -> str:
    l = links(pkg)
    mcp_servers = json.dumps({"mcpServers": {pkg: {"command": "uvx", "args": [pkg]}}}, indent=2)
    return f"""{START} (generated by scripts/gen_install.py; do not edit by hand) -->
Three steps. No accounts, no keys, no GPU.

**1. Install `uv`** (the tool that runs {pkg}; once per computer). Open a terminal (Windows: press Start, type
**PowerShell**, press Enter; macOS: open **Terminal**) and paste:

| Windows (PowerShell) | macOS / Linux |
|---|---|
| `powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 \\| iex"` | `curl -LsSf https://astral.sh/uv/install.sh \\| sh` |

Then **close the terminal and open a new one**, so it can find `uv`. `uvx --version` prints a version number when it's
ready.

**2. Add it to your AI app.** For Claude Code (already installed), one command finds a local model if you run one,
lists the optional tool groups (the ones it finds are ticked: press Enter to keep them), then asks before adding
HomeShed (answer **Y**):

{fence}bash
uvx {pkg} setup
{fence}

For Cursor, VS Code or Claude Desktop, click the button for your app (Claude Desktop's downloads `{pkg}.mcpb`:
double-click that file). Or add it to Claude Code yourself:

<p>
  <a href="{l['cursor']}"><img alt="Add to Cursor" src="https://cursor.com/deeplink/mcp-install-dark.svg" height="32"></a>
  <a href="{l['vscode']}"><img alt="Install in VS Code" src="https://img.shields.io/badge/VS_Code-Install-0098FF?style=for-the-badge&logo=visualstudiocode&logoColor=white"></a>
  <a href="{l['vscode_insiders']}"><img alt="Install in VS Code Insiders" src="https://img.shields.io/badge/VS_Code_Insiders-Install-24bfa5?style=for-the-badge&logo=visualstudiocode&logoColor=white"></a>
  <a href="https://github.com/keefng8/homeshed-mcp/releases/latest/download/{pkg}.mcpb"><img alt="Claude Desktop extension" src="https://img.shields.io/badge/Claude_Desktop-.mcpb-D97757?style=for-the-badge&logo=claude&logoColor=white"></a>
</p>

{fence}bash
claude mcp add -s user {pkg} -- uvx {pkg}
{fence}

**3. Quit your app fully, open it again, and try it in its chat** (Windows: right-click its icon by the clock and
choose Quit; macOS: Cmd+Q; Cursor and VS Code: use agent mode). These work straight away, with nothing else set up:

- *"What tools do you have from {pkg}?"*
- *"What are github.com's IP addresses?"*
- *"Is port 443 open on example.com?"*
- *"Use the logic solver: which whole numbers x and y give x + y = 10 and x − y = 4?"*
- *"What operating system and CPU is this machine running?"*

Stuck? If the terminal says `uvx` isn't recognised or not found, open a new terminal and try again. Then run
`uvx {pkg} doctor`: it checks everything and gives you the exact command to fix anything that's missing. If your app
can't start `uvx` (common for apps opened from the macOS Dock), put the full path that `which uvx` prints into its MCP
settings in place of `uvx`.

<details><summary><b>Other apps and install methods</b> (Codex, Gemini CLI, Claude Desktop, Windsurf, Cline, Zed, OpenCode, Goose, pip)</summary>

#### One-line commands

| Client | Command |
|---|---|
| Codex CLI | `codex mcp add {pkg} -- uvx {pkg}` |
| Gemini CLI | `gemini mcp add {pkg} uvx {pkg}` |
| VS Code | `code --add-mcp '{compact({"name": pkg, "command": "uvx", "args": [pkg]})}'` |
| Run it directly | `uvx {pkg}` · `pipx run {pkg}` · `pip install {pkg} && {pkg}` (in a virtual environment) |

#### Claude Desktop

Easiest: download `{pkg}.mcpb` from the [latest release](https://github.com/keefng8/homeshed-mcp/releases/latest) and
double-click it. Or add this to `claude_desktop_config.json` (Settings → Developer → Edit Config):

{fence}json
{mcp_servers}
{fence}

The same `mcpServers` block works in **Cursor** (`~/.cursor/mcp.json`), **Windsurf**
(`~/.codeium/windsurf/mcp_config.json`) and **Cline** (MCP Servers → Configure).

#### VS Code (`.vscode/mcp.json`)

{fence}json
{json.dumps({"servers": {pkg: {"type": "stdio", "command": "uvx", "args": [pkg]}}}, indent=2)}
{fence}

#### Zed (`settings.json`)

{fence}json
{json.dumps({"context_servers": {pkg: {"source": "custom", "command": "uvx", "args": [pkg]}}}, indent=2)}
{fence}

#### OpenCode (`opencode.json`)

{fence}json
{json.dumps({"mcp": {pkg: {"type": "local", "command": ["uvx", pkg], "enabled": True}}}, indent=2)}
{fence}

#### Goose (`~/.config/goose/config.yaml`; on Windows `%APPDATA%\\Block\\goose\\config\\config.yaml`)

{fence}yaml
extensions:
  {pkg}:
    type: stdio
    name: {pkg}
    enabled: true
    cmd: uvx
    args: [{pkg}]
    timeout: 300
{fence}

#### Codex (`~/.codex/config.toml`)

{fence}toml
[mcp_servers.{pkg}]
command = "uvx"
args = ["{pkg}"]
{fence}

No `uv` yet? [Install it](https://docs.astral.sh/uv/getting-started/installation/) with one command.
</details>

<details><summary><b>Want more? Connect your own model, cloud keys, or switch on write tools</b></summary>

Pass settings as environment variables, for example with `-e` in `claude mcp add`:

{fence}bash
claude mcp add -s user {pkg} -e LOCAL_AI_BASE_URL=http://localhost:11434/v1 -- uvx {pkg}
{fence}

| Setting | What it does |
|---|---|
| `LOCAL_AI_BASE_URL` | Your OpenAI-compatible model server (Ollama, llama.cpp, LM Studio…) |
| `LOCAL_AI_MODEL` | Which model on that server to use (needed with `LOCAL_AI_BASE_URL`; `setup` prints both) |
| `NVIDIA_API_KEY`, `GROQ_API_KEY`, `OPENROUTER_API_KEY`, `MISTRAL_API_KEY`, `GEMINI_API_KEY`, `OVH_AI_ENDPOINTS_TOKEN` | Cloud providers you choose to use, with your own keys ([all settings](docs/configuration.md)) |
| `ENABLE_TOOLS` | Switch on write tools, e.g. `git.commit,git.push` or a whole group, `git.*` (`dev.*` runs code: opt in only if you mean it) |
| `DATA_DIR`, `MEMORY_DB_PATH` | Where it keeps its data and memory |

> **Keep keys out of config files.** A key passed with `-e` is saved in plain text in that client's config. Where
> your client supports it, point at an environment variable instead, and never commit a config that holds a key.
</details>
{END}"""


def splice(readme: str, new: str) -> str:
    i, j = readme.find(START), readme.find(END)
    if i < 0 or j < i:
        raise SystemExit(f"README is missing the {START} ... {END} markers")
    return readme[:i] + new + readme[j + len(END):]


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--package", required=True, help="PyPI package and command name")
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--check", action="store_true", help="exit 1 if the README is stale")
    a = p.parse_args(argv)
    old = a.readme.read_text(encoding="utf-8")
    new = splice(old, block(a.package))
    if a.check:
        if new != old:
            print("README install section is stale: run python scripts/gen_install.py", file=sys.stderr)
            return 1
        return 0
    a.readme.write_text(new, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
